### ISSUE TITLE
Build failure without ladspa-sdk installed

### ISSUE THREAD

**Issue by daschuer** [breakfastquay/rubberband#32]
This should be checked in the configure script. 

```
In file included from ladspa/RubberBandPitchShifter.cpp:24:
ladspa/RubberBandPitchShifter.h:27:10: fatal error: ladspa.h: Datei oder Verzeichnis nicht gefunden
   27 | #include <ladspa.h>
      |          ^~~~~~~~~~
compilation terminated.
```

Tested with current master branch on Ubuntu Focal 20.4

**Comment by cannam** [comment]
Fixed in default branch, thanks. The configure script was already testing for `ladspa.h`, but it didn't do anything if it wasn't found! It now fails - there is (and already was) a `--disable-ladspa` option if you want to go ahead without it.

**Comment by naabtog** [comment]
I installed `ladspa-sdk`, `ladspa.h` is in `/usr/include` but I still get this error. Rubberband `955a32f`, Lubuntu 20.04.1
